version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecolink-backend
    ports:
      - "8011:8011"
    environment:
      - DATABASE_URL=postgresql://postgres:yourpassword@db/yourdatabase #Alterar antes do build
    volumes:
      - .:/app
    restart: always
