"""Alter open_time and close_time to Time

Revision ID: 5b1ed032c37d
Revises: 02446ab185ea
Create Date: 2024-11-22 22:58:07.564386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1ed032c37d'
down_revision: Union[str, None] = '02446ab185ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cooperative', 'open_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('cooperative', 'close_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cooperative', 'close_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('cooperative', 'open_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
